### ISSUE TITLE
Is the Arrow only showing for the Light theme?

### ISSUE THREAD

**Issue by ricardoalcocer** [manumaticx/Ti.DrawerLayout-Demo-Alloy-App#4]
It's not showing for me with this code

``` javascript
   var drawer = TiDrawerLayout.createDrawer({
            leftView: menuTable,
            centerView: contentView,
            leftDrawerWidth: "240dp",
            width: Ti.UI.FILL,
            height: Ti.UI.FILL,
            drawerArrowIcon : true
    });
```

This is what I see:

![](http://sht.tl/i9suvg)

**Comment by manumaticx** [comment]
I've tested this. It works for me with the Dark theme and custom themes.

Did you use `Theme.AppCompat.Dark` or `Theme.AppCompat.Light.DarkActionBar` as the parent of your Theme?

Did you set this `actionBar.displayHomeAsUp = true;` ?

**Comment by ricardoalcocer** [comment]
That was it.  It's not theme/style related.  You absolutely need to add the displayHomeAsUp.

**Comment by manumaticx** [comment]
Ah okay, I should mention this in the readme and the update the sample code in the module repo.
