### ISSUE TITLE
cannot call method 'setActive' of undefined on selected.setAcvtive(true)

### ISSUE THREAD

**Issue by ranggamp** [manumaticx/Ti.DrawerLayout-Demo-Alloy-App#5]
Hi, manumaticx. Thanks for your attention.
I was build an apps based on this demo. I tried to create third controller deep using Alloy.Globals.open(controllername,backstack true) as your function on Alloy.js, but there's a bug on them.
If I created third controller from second controller which the second are created from menu controller, then back button on android call this method on menu.js which can cause this error, but if i continue with the error, the apps still go on previous controller.
Any advice of this?

Thanks

**Comment by manumaticx** [comment]
How can I reproduce this with the demo app?

**Comment by ranggamp** [comment]
Thanks manu,
check this simple examples that i modified from yours..
https://github.com/ranggamp/demo-manu
I created button on home that create Alloy controller window1, hit android back button OK.
but when i click button on window1 that creates window2, hit android back button on window2 given error such as i described earlier... 
Can you give any advice, please...
thanks

**Comment by manumaticx** [comment]
I see.

In this demo, the `Alloy.Globals.open` method was intended to switch the content views that are represented in the menu. 

There are two solutions for this:
1. You could wrap your sub-windows with `Ti.UI.Window` and open them as new activities (`window.open();`).
2. You could change the menu controller to ignore controllers that are no menu items. Therefor you'd change [this line](https://github.com/ranggamp/demo-manu/blob/master/app/controllers/menu.js#L70) to this:

``` js
!!row && selectRow(row, _cb, _addToBackstack);
```

I hope this answers your question. If not, let me know.

**Comment by ranggamp** [comment]
Thanks, Manu... It work like a charm..
I think this also a solution if anybody wants to do same as opening second window or something..

Godbless you....

**Comment by manumaticx** [comment]
Glad to help. Nice to hear that it works for you :v:
