### ISSUE TITLE
Problem with style and ActionBar

### ISSUE THREAD

**Issue by bcarvalho89** [manumaticx/Ti.DrawerLayout-Demo-Alloy-App#6]
Hello.

I cloned the repository and test in emulator, but I had two problems:
1. Is there a problem in themes.xml file, it is not applying the defined styles. Thus, the color of the ActionBar and the item `android:windowTranslucentStatus` not work.
2. The other problem is that the ActionBar is not being updated when select a menu item. The title and items (icons) that appear are the main view.

![image](https://cloud.githubusercontent.com/assets/8310877/13901495/92cf29cc-ee04-11e5-84c0-ba39a764ed8a.png)

Installing wintest.apk which is by the repository, issue 1 does not exist, but the 2 continues.

Could help me?

System
Windows 8.1 64
Appcelerator Studio 4.5.0.2
Titanium SDK 5.2.0 - 5.1.1 - 5.1.0
Device: Genymotion Nexus 4 - Android 5 / Genymotion Galaxy S6 - Android 6

Thanks.

**Comment by manumaticx** [comment]
Hi @bcarvalho89 

sorry for the late reply.
1. You have to ensure, that Titanium is packaging the local module here. If it picks the globally installed version of Ti.DrawerLayout it's not working. Please note that I also modified the content of [drawer_main.xml](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App/blob/master/modules/android/com.tripvi.drawerlayout/1.3.6/platform/android/res/layout/drawer_main.xml) within the local module.
2. This was my mistake. I removed too much of the old code. I'll push a fix in a sec.

**Comment by manumaticx** [comment]
that should work.

**Comment by bcarvalho89** [comment]
1 - You are correct. The problem was in global module.
2 - Your update works like a charm ;)

Thanks for reply and attention.

**Comment by MahmoudElmoghazy** [comment]
@manumaticx I didn't understande the answer i have the same issue

**Comment by manumaticx** [comment]
@MahmoudElmoghazy the Theme issue or the actionbar update issue?

**Comment by MahmoudElmoghazy** [comment]
@manumaticx The action bar doesn't take any color from my theme file

**Comment by manumaticx** [comment]
Okay, I already fixed this [here](https://github.com/manumaticx/Ti.DrawerLayout/commit/77988ef048b4b3324bf69226fcc633a08e5b4407) but I didn't update the module yet. I also have to document this. I know, I'm lazy ;)

You can work around this by installing the latest version of the Ti.DrawerLayout module _locally_ as I did here in this demo app. And then go into `{project root}/modules/android/com.tripvi.drawerlayout/1.3.6/platform/android/res/layout` and adjust the `drawer_main.xml` like here: https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App/blob/master/modules/android/com.tripvi.drawerlayout/1.3.6/platform/android/res/layout/drawer_main.xml
